# Generated by Django 6.0.3 on 2026-05-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='message',
            new_name='complaint',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='feedback',
        ),
    ]
