# Generated by Django 6.0.3 on 2026-05-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_payment_fine_amount_payment_payment_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='dashboard.payment')),
            ],
        ),
    ]
