# Generated by Django 6.0.3 on 2026-05-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_payment_payment_completed_payment_remaining_amount_and_more'),
        ('users', '0003_house_is_rental_house_owner_contact_house_owner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentpayment',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='installmentpayment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='remaining_amount',
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('previous_reading', models.IntegerField()),
                ('current_reading', models.IntegerField()),
                ('units_consumed', models.IntegerField()),
                ('rate_per_unit', models.IntegerField(default=8)),
                ('total_amount', models.IntegerField()),
                ('remaining_amount', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.house')),
            ],
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='electricity_bill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='dashboard.electricitybill'),
            preserve_default=False,
        ),
    ]
