# Generated by Django 6.0.3 on 2026-05-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_installmentpayment_payment_and_more'),
        ('users', '0003_house_is_rental_house_owner_contact_house_owner_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('fine_amount', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paymentcategory')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.house')),
            ],
        ),
    ]
