# Generated by Django 6.0.3 on 2026-05-07 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhar_pan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid 10 digit phone number', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
