# Generated by Django 6.0.3 on 2026-05-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_aadhar_pan_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='owner_contact',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='owner_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='rent_price',
            field=models.IntegerField(default=0),
        ),
    ]
